db_cache:
  maxsize: 104857600
  ttl: 48h0m0s
  enabledtables:
  - users
  - products
  strategy: lru
  stats:
    lastreset: 2025-02-23T14:48:22.6284339+01:00
    totalhits: 1
    totalmisses: 0
web_server:
  host: localhost
  port: 8080
  requesttimeout: 30s
  maxconnections: 2000
  enablehttps: false
  certificatepath: /etc/certs/server.pem
